name: Bump Release from Tag

on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Extract version from tag
        id: extract
        run: |
          TAG=${{ github.ref_name }}
          VERSION=${TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Bump API package.json version to ${{ env.VERSION }}
        run: npm version $VERSION --no-git-tag-version

      - name: Switch to client directory
        run: cd ../client

      - name: Bump client package.json version to ${{ env.VERSION }}
        run: npm version $VERSION --no-git-tag-version
        working-directory: ./client

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: bump version to $VERSION"
          git push

      - name: Move tag to version bump commit
        run: |
          git tag -d ${{ github.ref_name }} || true
          git push origin :refs/tags/${{ github.ref_name }} || true
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}
