name: Client Linters

on:
  push:
    branches: [main]
    paths:
      - "client/**"
  pull_request:
    branches: [main]
    paths:
      - "client/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  client-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Cache node_modules folder
        uses: actions/cache@v4
        id: cache
        with:
          path: client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Linters
        run: |
          npm run prettier:check
          npm run lint:check
          npx tsc --noEmit
